version: '3'
services:
  user-service:
    build: ./user_service
    ports:
      - "8000:8000"
  product-service:
    build: ./product_service
    ports:
      - "8001:8001"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
